"""add tickets table

Revision ID: 8a677d0cf7fe
Revises: 
Create Date: 2025-07-30 17:01:04.282454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a677d0cf7fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=False),
    sa.Column('category', sa.VARCHAR(length=15), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_tickets_organization_id_organizations'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_tickets_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_tickets')
    )
    op.create_index('ix_tickets_id', 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_id', table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
