CREATE TABLE IF NOT EXISTS history_piping (
                                          id SERIAL PRIMARY KEY,
                                          name VARCHAR(255) NOT NULL,
                                          plant_id VARCHAR(50) ,
                                          equipment_num VARCHAR(50) NOT NULL,
                                          equipment_name VARCHAR(100) NOT NULL,
                                          equipment_type VARCHAR(50) NOT NULL CHECK (equipment_type IN ('Piping')),
                                          date DATE NOT NULL,
                                          P FLOAT NOT NULL,
                                          D FLOAT NOT NULL,
                                          S FLOAT NOT NULL,
                                          E FLOAT NOT NULL,
                                          c FLOAT NOT NULL,
                                          t FLOAT NOT NULL,
                                          tm FLOAT NOT NULL,
                                          t_int FLOAT NOT NULL,
                                          t_act FLOAT NOT NULL,
                                          time_years INTEGER NOT NULL,
                                          corrosion_rate FLOAT NOT NULL,
                                          corrosion_type VARCHAR(20),
                                          remaining_life FLOAT NOT NULL,
                                          next_inspection_year INTEGER NOT NULL,
                                          inspection_interval INTEGER NOT NULL,
                                          timestamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS history_PV (
                                          id SERIAL PRIMARY KEY,
                                          name VARCHAR(255) NOT NULL,
                                          plant_id VARCHAR(50) ,
                                          equipment_num VARCHAR(50) NOT NULL,
                                          equipment_name VARCHAR(100) NOT NULL,
                                          equipment_type VARCHAR(50) NOT NULL CHECK (equipment_type IN ('Pressure Vessel')),
                                          date DATE NOT NULL,
                                          P FLOAT NOT NULL,
                                          R FLOAT NOT NULL,
                                          S FLOAT NOT NULL,
                                          E FLOAT NOT NULL,
                                          c FLOAT NOT NULL,
                                          t FLOAT NOT NULL,
                                          tm FLOAT NOT NULL,
                                          t_int FLOAT NOT NULL,
                                          t_act FLOAT NOT NULL,
                                          time_years INTEGER NOT NULL,
                                          corrosion_rate FLOAT NOT NULL,
                                          corrosion_type VARCHAR(20),
                                          remaining_life FLOAT NOT NULL,
                                          next_inspection_year INTEGER NOT NULL,
                                          inspection_interval INTEGER NOT NULL,
                                          timestamp TIMESTAMP NOT NULL
);
