services:
  # Backend API Service
  - type: web
    name: vessel-guard-backend
    env: python
    plan: starter
    buildCommand: |
      cd apps/backend
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: |
      cd apps/backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vessel-guard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://vessel-guard-frontend.onrender.com
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Web Service
  - type: web
    name: vessel-guard-frontend
    env: node
    plan: starter
    buildCommand: |
      cd apps/frontend
      npm ci
      npm run build
    startCommand: |
      cd apps/frontend
      npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://vessel-guard-backend.onrender.com
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: vessel-guard-db
    databaseName: vesselguard
    user: vesselguard_user
    plan: starter 